name: multi_image_picker3
description: Flutter plugin that allows you to display multi image picker on iOS and Android.
version: 5.0.02
homepage: https://github.com/praveen-nex/multi_image_picker3

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

# The following section is specific to Flutter.
flutter:
  plugin:
    platforms:
      android:
        package: com.vitanov.multiimagepicker
        pluginClass: MultiImagePickerPlugin
      ios:
        pluginClass: MultiImagePicker3Plugin

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.12.13 <2.0.0"
